# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: Install Some Dependencies
        run: |
          sudo apt-get install dpkg-dev dpkg-sig
      - name: Import My GPG Key
        run: |
          echo $PRIVATE_KEY > private.key
          export KEYNAME=$(gpg --import private.key 2>/dev/stdout \
            | grep "secret key imported" \
            | sed "s/gpg: key //g" \
            | sed "s/: secret key imported//g")
          echo "::set-env name=KEYNAME::$KEYNAME"
        env:
          PRIVATE_KEY: ${{ variables.PRIVATE_KEY }}
      - name: Get Latest Discord DEB
        run: |
          wget "https://discord.com/api/download?platform=linux&format=deb" -O discord.deb
      - name: Extract Package Metadata
        run: |
          ar vx discord.deb
          tar -xvzf control.tar.gz control && rm control.tar.gz
          mkdir --parents dists/latest/amd64
          mv discord.deb dists/latest/amd64
          mv control dists/latest/Release
      - name: Setup Debian Repository
        run: |
          cd dists/latest
          apt-ftparchive --arch amd64 packages amd64 > Packages
          gzip -k -f Packages
          apt-ftparchive release . >> Release
          gpg --default-key $KEYNAME -abs -o Release.gpg Release
          gpg --default-key $KEYNAME --clearsign -o InRelease Release
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
